### ISSUE TITLE
add the UUID as an annotation/metadata for Open Telemetry

### ISSUE THREAD

**Issue by AniaMakes** [Financial-Times/dotcom-reliability-kit#1024]
A clear and concise description of the requested feature. Please try to complete the sections below, but feel free to remove if they're not relevant to your feature request.

## What problem does this feature solve?
We would like to search by user ID to find the calls a specific user journey makes. Andy and I had a poke around the next-newsletter-signup data bucket the other day and it was very hard to figure out what it could be useful for - but if we had user ID (uuid), then we would be able to more granularly track a user journey (Amplitude can be a bit funny) and debug problems that are reported. Thank you!

## Ideal solution
Alex suggested that this can be done by adding the UUID as an annotation/metadata for Open Telemetry (https://financialtimes.slack.com/archives/C02B89GEQHF/p1714480091266369)

## Alternatives
n/a

**Comment by rowanmanning** [comment]
Correct me if I'm wrong but this _feels_ like a similar issue to #901 - both are asking about adding further metadata to traces. If I'm incorrect then let me know and we can maybe reopen this.
