### ISSUE TITLE
Allow adding custom log serializers

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/dotcom-reliability-kit#1248]
Add the ability to instantiate a logger with custom serializers.

## What problem does this feature solve?

We're seeing people extend our logger to reduce repetition in their code, mostly this seems to be to convert more complex objects to a JSON-compatible structure for logging.

## Ideal solution

I don't want to add any more default serializers as this is more work to maintain and a load more code. I think the best thing would be to allow setting serializers when you instantiate a logger:

```js
const logger = new Logger({
    serializers: {
        // the property name corresponds to the property found in the log data
        fruit: (value) => value.name
    }
});

logger.info({ fruit: { name: 'Apple' } })
// { "fruit": "Apple" }
```

This will simplify internals because we can use the same system for serializing errors. We could also open this up to allow people to specify their own error serializers if they want to do some weird stuff:

```js
const logger = new Logger({
    serializers: {
        // Shouty error logging
        error: (error) => error.stack.toUpperCase()
    }
});
```

We could then really simplify the `log-error` package. Each method could just be pulled from a logger with new serializers. Something along these lines:

```js
const logger = new Logger({
    serializers: {
        request: serializeRequest
    }
});

const logHandledError = logger.createChildLogger({ event: 'HANDLED_ERROR' }).error;
const logRecoverableError = logger.createChildLogger({ event: 'RECOVERABLE_ERROR' }).warn;
const logUnhandledError = logger.createChildLogger({ event: 'UNHANDLED_ERROR' }).fatal;
```

We'd need to properly handle errors that occur in serialization because we'd be opening up the internals to code provided by our users. We're already doing this with [transforms](https://github.com/Financial-Times/dotcom-reliability-kit/tree/main/packages/logger#optionstransforms).

## Alternatives

TBH we _could_ maybe achieve this with transforms and no code changes. Technically this will also work:

```js
const logger = new Logger({
    transforms: [
        (logData) => {
            if (logData.fruit) {
                logData.fruit = fruit.name;
            }
            return logData;
        }
    ]
});
```

However:

  * you can't override the default serializers
  * This is probably also less efficient because _every_ transform in the array is executed even if the property it focuses on is not present
  * It's not as clear what's happening IMO

**Comment by kavanagh** [comment]
A downside to transformers is having a less predicable execution order for log masking. You'd want anything that is redacting logs to be downstream of the serializer functions, no?

The other consideration is, does this break the legacyMask transforms?

**Comment by kavanagh** [comment]
I was also wondering if there's a shorthand for anything that already has a useful `toJSON` or `valueOf()` method. Often it might just be like

```
const logger = new Logger({
    serializers: {
      fruit: (value) => value.toJSON(),
      vegetable: (value) => value.valueOf(),
    }
})
```

**Comment by rowanmanning** [comment]
Yep I think I'm anti reusing transformers for this. I reckon serializers need to be run _before_ transforms to make sure that you can't break the masking 👍

You already get `toJSON` for free because Pino respects these methods.
