### ISSUE TITLE
Switch types to use overloads for some of our more complex functions

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/dotcom-reliability-kit#450]
Overhaul our types in places where overloading could be used.

> **Warning**
> This work cannot be completed until we've migrated to TypeScript 5.0, which is possible once #461 and #462 are merged and released

## What problem does this feature solve?

Currently TypeScript + JSDoc doesn't support [function overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads). Support [will be added in TypeScript v5](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#overload-support-in-jsdoc), and we can probably reduce the complexity of some of our types by adopting this.

## Ideal solution

Ideally we'd review all places around the code where we currently use [union types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types) (e.g. `string | number`). Once we've looked at how these are used we can decide which ones we want to adapt. It may be that some of the changes would be breaking and require major version bumps.

## Alternatives

We could do nothing here, it doesn't hurt us that much but we lose out on our engineers getting clearer documentation and type hinting in their editors.

**Comment by CyntiBinti** [comment]
issue closed with merged PR #638. Discussed with @rowanmanning that there doesn't seem to be any other relevant union type params at this moment in the codebase, but good to bare in mind for future complex functions handling changing param data/types

**Comment by CyntiBinti** [comment]
[JIRA](https://financialtimes.atlassian.net/browse/CPREL-653)
