### ISSUE TITLE
Can we enable more flexibility with NODE_ENV?

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/dotcom-reliability-kit#476]
## What problem does this feature solve?

https://github.com/Financial-Times/dotcom-reliability-kit/blob/f4fb427b50302ae6d25b800d9688a4c6013f5752/packages/app-info/lib/index.js#L68

Only three values are handled by the logger:
1) 'production'
2) null
3) 'development'
The aim being to only show `pino` pretty logs whilst working in `development`

## Ideal solution

We make extensive use of `test` as our pre-production value for `NODE_ENV`. It would be great if that was treated the same as development 😄 so we could see the pretty logs

## Alternatives

We could change all our references from `test` to `development` but our environments and aws phases are named in the same way using `test` and `production` 🤔

**Comment by rowanmanning** [comment]
Hey Geoff 👋 I'm happy for logs in the `test` environment to also get prettified. It'd be a relatively simple change, [this line](https://github.com/Financial-Times/dotcom-reliability-kit/blob/f4fb427b50302ae6d25b800d9688a4c6013f5752/packages/logger/lib/logger.js#L108) (and relevant tests) needs updating to also return true if the value is `test`.

I might get to this at some point but also happy for you to open a pull request.

**Comment by GeoffThorpeFT** [comment]
https://github.com/Financial-Times/dotcom-reliability-kit/pull/481
