### ISSUE TITLE
We now see ESLint warnings for some JSDoc type annotations

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/dotcom-reliability-kit#509]
Since #507 we see a lot of ESLint warnings for our object types. E.g.

```
warning  Use object shorthand or index signatures instead of `Object`, e.g., `{[key: string]: string}`
```

This is because of a breaking change in [v41 of the plugin](https://github.com/gajus/eslint-plugin-jsdoc/releases/tag/v41.0.0) we use combined with the fact we enable the plugin's TypeScript mode.

**Node.js version:** all
**Impacted package(s):** all

## Steps to reproduce

1. Run `npm run lint`
2. See warnings

## Expected behaviour

I'd expect us not to have a bunch of fixable warnings. We should decide whether we want to disable TypeScript mode _or_ switch all our types to be more like TypeScript. If we decide the latter then we'd need to change things in the JSDoc like:

```
Object<string, string>
```

to:

```
{[key: string]: string}
```

If we were doing this then I'd probably suggest also changing our array notation from this:

```
Array<string>
```

to this:

```
string[]
```

**Comment by rowanmanning** [comment]
I'd vote for option 2: making our existing Types more TypeScript-looking as I think the syntax is better-understood than JSDoc

**Comment by CyntiBinti** [comment]
This has now been fixed :)
