### ISSUE TITLE
Refactor code to use some of the new Node.js 16+ features

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/dotcom-reliability-kit#527]
Now that we've dropped Node.js 14 support, we can use some of the features that were released in Node.js 15 and 16. This will generally improve the code and it's a nice introduction to working in the repo.

## What problem does this feature solve?

We keep the code modern and we get the benefits outlined in [this blog post](https://financialtimes.atlassian.net/wiki/spaces/DS/blog/2023/04/19/8045723685/The+features+we+gain+from+the+Node.js+14+sunset).

## Ideal solution

Probably a series of small PRs adding different features.

## Alternatives

We could not actively do this work and just update when we touch files. That's fine, but will leave this issue open in case someone wants to start contributing to Reliability Kit this way.

**Comment by CyntiBinti** [comment]
Gone through reliability kit with @Shamarni96 and found that the new methods from this [blog post](https://financialtimes.atlassian.net/wiki/spaces/DS/blog/2023/04/19/8045723685/The+features+we+gain+from+the+Node.js+14+sunset) aren't relevant for our code base. So this issue can now be closed

**Comment by rowanmanning** [comment]
I think you're mostly right based on our chat but there's one thing from the blog that I can see from a glance: replacing some built-in module references with the `node:`-prefixed versions. The built-in modules we use which could be updated are: `path`, `http`, `child_process`, `fs`, and `fs/promises`, e.g.

```js
const path = require('path');
```

would become:

```js
const path = require('node:path');
```
