### ISSUE TITLE
Calling Logger.log results in a broken error message

### ISSUE THREAD

**Issue by alexmuller** [Financial-Times/dotcom-reliability-kit#547]
`Logger.log` is a public method but when calling it the `LOG_LEVEL_DEPRECATED` event will log with a message of:

```
The '[object Object]' log level is deprecated
```

**Node.js version:** 20
**Impacted package(s):** Logger

## Steps to reproduce

```
const logger = require('@dotcom-reliability-kit/logger');
logger.log({foo: 'bar'});
{"level":"warn","time":1682695663056,"event":"LOG_LEVEL_DEPRECATED","message":"The '[object Object]' log level is deprecated","deprecatedLevel":{"foo":"bar"},"suggestedLevel":"info"}
```

## Expected behaviour

Either `Logger.log` is not deprecated or the error message doesn't contain `[object Object]`.

**Comment by rowanmanning** [comment]
`Logger.prototype.log` expects 2+ arguments, the first is a `String` (the log level) and the rest of the arguments are for log data. See [JSDoc here](https://github.com/Financial-Times/dotcom-reliability-kit/blob/main/packages/logger/lib/logger.js#L331).

Do you think [the docs](https://github.com/Financial-Times/dotcom-reliability-kit/blob/main/packages/logger/README.md#loggerlog-and-shortcut-methods) for this are clear enough? Maybe they need some clarification.

If you just want to pass an object then you need one of the shortcut methods, e.g.

```
const logger = require('@dotcom-reliability-kit/logger');
logger.info({foo: 'bar'});
{"level":"info","time":123456,"foo":"bar"}
```

Maybe the real work here is to error differently if the log level is not a string?
