### ISSUE TITLE
The logger is broken for apps using native ES Modules

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/dotcom-reliability-kit#578]
As outlined in [this Slack thread](https://financialtimes.slack.com/archives/C02B89GEQHF/p1684248616540489), the logger does not work when used in native ES modules. That's because we're using `require` [here](https://github.com/Financial-Times/dotcom-reliability-kit/blob/93400b50d48b83da17e3377ba76013419ab879b4/packages/logger/lib/logger.js#L105). This is my fault, I'm sorry.

**Node.js version:** All
**Impacted package(s):** Logger

## Steps to reproduce

1. Install the logger in an app which uses native ES Modules

2. Import with logger

3. You should see an unhandled rejection

## Expected behaviour

The logger should work with native ES Modules. We can get around this by using the `import()` function which is available in both ES Modules and CommonJS. It just requires a bunch of refactoring because our code has to be async for this to work. Ugh.

**Comment by alexmuller** [comment]
Can we/do we want to do anything around integration tests with installing the logger in every possible module system?

**Comment by rowanmanning** [comment]
[Something like this](https://github.com/Financial-Times/dotcom-reliability-kit/issues/303)? 😁

**Comment by rowanmanning** [comment]
OK this isn't strictly true and I need to investigate more. I think it might be when TypeScript compiles to native ESM rather than native ESM itself. Fun! The following works fine for me:

1. Create a new folder and add a file named `test.mjs` containing the following:

      ```js
      import logger from '@dotcom-reliability-kit/logger';
      logger.info('Hello world!');
      ```

2. Run `npm install @dotcom-reliability-kit/logger`

3. Run `node test.mjs`

Everything works.

**Comment by rowanmanning** [comment]
OK this turned out to be an issue with ESBuild which, for a Lambda, was bundling all of the dependencies into a single file which is more what we'd expect for client-side JS. This isn't a target I want to try and support in Reliability Kit as I wouldn't expect us to be doing this on the server side.
