### ISSUE TITLE
Subsequent logs missing after attempting to log large amounts of info from a lambda

### ISSUE THREAD

**Issue by andy-little** [Financial-Times/dotcom-reliability-kit#726]
**Node.js version:** 14 
**Impacted package(s):** logger

We found a quirk with logging in lambdas. We were logging out the parameters sent to a write transaction to dynamoDB. We noticed that when the params were **very** large, we would get no further logs thereafter. In the particular case we noticed this behaviour we were logging in a catch block. We were expecting the error to propagate through and trigger another log but it looks like the lambda might have been terminated before the logger got a chance to write the logs …maybe?

[This ticket ](https://financialtimes.atlassian.net/browse/EI-4176)explains in more detail and links to the logs in cloud watch and Splunk.

**Comment by rowanmanning** [comment]
Hiya I'm going to close this for now as, after reading your ticket, it seems like you're hitting the Splunk log size limit? I've been thinking about whether it'd be possible to detect when a log is larger than the size limit but it's not gonna be super easy (and may not be possible).
