### ISSUE TITLE
logger does not output the contents of property `name`

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/dotcom-reliability-kit#937]
**Node.js version:** 18
**Impacted package(s):** logger

## Steps to reproduce

With the following code:

```
	console.log("@@@@@@@@@@@@@@@@@@@@@@@@@@@")
	console.log(app.id)
	console.log(app.name)
	console.log("@@@@@@@@@@@@@@@@@@@@@@@@@@@")
	logger.info({
		event: 'STARTING_APP_ANALYSIS',
		name: app.name,
		id: app.id,
		progress: count,
		target: apps.length,
	})
```

The `console.log` outputs the contents of `app.name` whereas the `logger.info` does not output the `name` property - just the `id`, `progress` and `target`.  If I use a value different to `name` eg `geoff` then the contents of app.name is output

**Comment by rowanmanning** [comment]
Confirmed with @GeoffThorpeFT that `name` gets moved when pino-pretty is enabled but it does appear in the JSON when you disable the prettifier. Might be that we can stop it from doing this.

**Comment by rowanmanning** [comment]
This is similar to #1069, I think it's not solvable unfortunately. The data _does_ appear in production so I'm not particularly worried about it.
